import 'package:kinda_work/models.dart';

List<InfoElement> popularPlaces = [
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'ЧистоМойка',
    rate: 5.3,
    countMessages: 200,
    isDiscountVisible: true,
    discount: 50,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/2.png',
    isFavoriteVisible: true,
    isFavorite: true,
    lightText: 'Салон красоты',
    boltText: 'Bojoli',
    rate: 9.5,
    countMessages: 567,
    isDiscountVisible: true,
    discount: 55,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/3.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Ресторан',
    boltText: 'Хижина',
    rate: 8.8,
    countMessages: 35,
    isDiscountVisible: true,
    discount: 30,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/no_photo.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'GreatМойка',
    rate: 0.0,
    countMessages: 1,
    isDiscountVisible: true,
    discount: 25,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'ЧистоМойка',
    rate: 5.3,
    countMessages: 200,
    isDiscountVisible: true,
    discount: 60,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/2.png',
    isFavoriteVisible: true,
    isFavorite: true,
    lightText: 'Салон красоты',
    boltText: 'Bojoli',
    rate: 9.5,
    countMessages: 567,
    isDiscountVisible: true,
    discount: 75,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/3.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Ресторан',
    boltText: 'Хижина',
    rate: 8.8,
    countMessages: 35,
    isDiscountVisible: true,
    discount: 45,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/no_photo.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'GreatМойка',
    rate: 0.0,
    countMessages: 1,
    isDiscountVisible: true,
    discount: 50,
  ),
];

List<InfoElement> popularPromotions = [
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Всё меню и напитки в ресторане грузинско...',
    rate: 4.2,
    countMessages: 26,
    discount: 50,
    isDiscountVisible: true,
    //TODO make right format to this prices
    newPrice: '120 540',
    oldPrice: '130 565',
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/2.png',
    isFavoriteVisible: true,
    isFavorite: true,
    lightText: 'Блюда и напитки в сети кафе "Шантимель" со...',
    rate: 0.0,
    countMessages: 2,
    discount: 50,
    isDiscountVisible: true,
    newPrice: '230',
    oldPrice: '265',
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Всё меню и напитки в ресторане грузинско...',
    rate: 4.2,
    countMessages: 26,
    discount: 50,
    isDiscountVisible: true,
    //TODO make right format to this prices
    newPrice: '120 540',
    oldPrice: '130 565',
  ),
  // InfoElement(
  //   isLargeGridElement: false,
  //   img: 'assets/png/grid/2.png',
  //   isFavoriteVisible: true,
  //   isFavorite: true,
  //   lightText: 'Блюда и напитки в сети кафе "Шантимель" со...',
  //   rate: 0.0,
  //   countMessages: 2,
  //   discount: 50,
  //   isDiscountVisible: true,
  //   newPrice: '230',
  //   oldPrice: '265',
  // ),
  // InfoElement(
  //   isLargeGridElement: false,

  //   img: 'assets/png/grid/1.png',
  //   isFavoriteVisible: true,
  //   isFavorite: false,
  //   lightText: 'Всё меню и напитки в ресторане грузинско...',
  //   rate: 4.2,
  //   countMessages: 26,
  //   discount: 50,
  //   isDiscountVisible: true,

  //   //TODO make right format to this prices
  //   newPrice: '120 540',
  //   oldPrice: '130 565',
  // ),
  // InfoElement(
  //   isLargeGridElement: false,
  //   img: 'assets/png/grid/2.png',
  //   isFavoriteVisible: true,
  //   isFavorite: true,
  //   lightText: 'Блюда и напитки в сети кафе "Шантимель" со...',
  //   rate: 0.0,
  //   countMessages: 2,
  //   discount: 50,
  //   isDiscountVisible: true,
  //   newPrice: '230',
  //   oldPrice: '265',
  // ),
  // InfoElement(
  //   isLargeGridElement: false,

  //   img: 'assets/png/grid/1.png',
  //   isFavoriteVisible: true,
  //   isFavorite: false,
  //   //TODO create ... if text sentence too long
  //   lightText:
  //       'Всё меню и напитки принимаются и выдаются исключительно бесплатно и навсегда',
  //   rate: 4.2,
  //   countMessages: 27,
  //   discount: 50,
  //   isDiscountVisible: true,

  //   //TODO make right format to this prices
  //   newPrice: '120 540',
  //   oldPrice: '130 565',
  // ),
  // InfoElement(
  //   isLargeGridElement: false,
  //   img: 'assets/png/grid/2.png',
  //   isFavoriteVisible: true,
  //   isFavorite: true,
  //   lightText: 'Блюда и напитки в сети кафе "Шантимель" со...',
  //   rate: 0.0,
  //   countMessages: 2,
  //   discount: 50,
  //   isDiscountVisible: true,
  //   newPrice: '230',
  //   oldPrice: '265',
  // ),
];
