import 'package:flutter/material.dart';
import 'package:latlong/latlong.dart';

import 'package:kinda_work/models.dart';

List<InfoElement> popularPlaces = [
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'ЧистоМойка',
    rate: 5.3,
    countMessages: 200,
    isDiscountVisible: true,
    discount: 50,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/2.png',
    isFavoriteVisible: true,
    isFavorite: true,
    lightText: 'Салон красоты',
    boltText: 'Bojoli',
    rate: 9.5,
    countMessages: 567,
    isDiscountVisible: true,
    discount: 55,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/3.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Ресторан',
    boltText: 'Хижина',
    rate: 8.8,
    countMessages: 35,
    isDiscountVisible: true,
    discount: 30,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/no_photo.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'GreatМойка',
    rate: 0.0,
    countMessages: 1,
    isDiscountVisible: true,
    discount: 25,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'ЧистоМойка',
    rate: 5.3,
    countMessages: 200,
    isDiscountVisible: true,
    discount: 60,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/2.png',
    isFavoriteVisible: true,
    isFavorite: true,
    lightText: 'Салон красоты',
    boltText: 'Bojoli',
    rate: 9.5,
    countMessages: 567,
    isDiscountVisible: true,
    discount: 75,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/3.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Ресторан',
    boltText: 'Хижина',
    rate: 8.8,
    countMessages: 35,
    isDiscountVisible: true,
    discount: 45,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/no_photo.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Автомойка',
    boltText: 'GreatМойка',
    rate: 0.0,
    countMessages: 1,
    isDiscountVisible: true,
    discount: 50,
  ),
];

List<InfoElement> popularPromotions = [
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Всё меню и напитки в ресторане грузинско...',
    rate: 4.2,
    countMessages: 26,
    discount: 50,
    isDiscountVisible: true,
    //TODO make right format to this prices
    newPrice: 120540,
    oldPrice: 130565,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/2.png',
    isFavoriteVisible: true,
    isFavorite: true,
    lightText: 'Блюда и напитки в сети кафе "Шантимель" со...',
    rate: 0.0,
    countMessages: 2,
    discount: 50,
    isDiscountVisible: true,
    newPrice: 230,
    oldPrice: 265,
  ),
  InfoElement(
    isLargeGridElement: false,
    img: 'assets/png/grid/1.png',
    isFavoriteVisible: true,
    isFavorite: false,
    lightText: 'Всё меню и напитки в ресторане грузинско...',
    rate: 4.2,
    countMessages: 26,
    discount: 50,
    isDiscountVisible: true,
    //TODO make right format to this prices
    newPrice: 120540,
    oldPrice: 130565,
  ),
];

List<InfoMarker> listInfoMarkers = [
  InfoMarker(
    id: 1,
    position: LatLng(53.912180, 27.545018),
    places: [
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: false,
        isFavoriteVisible: false,
        lightText: 'Массажный салон',
        img: 'assets/png/grid/2.png',
        rate: 9.5,
      ),
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: false,
        isFavoriteVisible: false,
        lightText: 'Фото салон',
        img: 'assets/png/grid/1.png',
        rate: 1.5,
      ),
    ],
    promotions: [
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: true,
        discount: 50,
        isFavoriteVisible: false,
        lightText: 'Романтический ужин',
        img: 'assets/png/grid/2.png',
        rate: 7.9,
        countMessages: 26,
        newPrice: 150,
        oldPrice: 200,
      ),
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: false,
        isFavoriteVisible: false,
        lightText: 'Романтический ужин',
        img: 'assets/png/grid/2.png',
        rate: 7.9,
        countMessages: 26,
        newPrice: 150,
        oldPrice: 200,
      ),
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: true,
        discount: 45,
        isFavoriteVisible: false,
        lightText: 'Романтический ужин',
        img: 'assets/png/grid/2.png',
        rate: 7.9,
        countMessages: 26,
        newPrice: 150,
        oldPrice: 200,
      ),
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: true,
        discount: 45,
        isFavoriteVisible: false,
        lightText: 'Романтический ужин',
        img: 'assets/png/grid/2.png',
        rate: 7.9,
        countMessages: 26,
        newPrice: 150,
        oldPrice: 200,
      ),
      InfoElement(
        isLargeGridElement: false,
        isDiscountVisible: true,
        discount: 45,
        isFavoriteVisible: false,
        lightText: 'Романтический ужин',
        img: 'assets/png/grid/2.png',
        rate: 7.9,
        countMessages: 26,
        newPrice: 150,
        oldPrice: 200,
      )
    ],
  ),
  InfoMarker(
    id: 2,
    position: LatLng(53.911080, 27.541718),
    places: [],
    promotions: [],
  ),
  InfoMarker(
    id: 3,
    position: LatLng(53.908580, 27.546318),
    places: [],
    promotions: [],
  ),
];

List<DiscountMarker> listDiscountMarkers = [
  DiscountMarker(discount: 95, position: LatLng(53.912280, 27.541818)),
  DiscountMarker(discount: 50, position: LatLng(53.911580, 27.547918)),
  DiscountMarker(discount: 15, position: LatLng(53.908380, 27.541318)),
];

List<Image> imagesMainPage = [
  Image.asset('assets/png/slider/slider1.png', fit: BoxFit.cover),
  Image.asset('assets/png/slider/slider2.png', fit: BoxFit.cover),
  Image.asset('assets/png/slider/slider3.png', fit: BoxFit.cover),
  Image.asset('assets/png/slider/slider4.png', fit: BoxFit.cover),
];
